@startuml

(*) --> "Login sebagai Guru"

if "Guru belum login" then
  -->[true] "Login sebagai Guru"
else
  -->[false] "Buat Soal Baru"
  --> "Tambah Pertanyaan"
  --> "Tambah Pilihan Jawaban"
  --> "Buat Kunci Jawaban"
  --> "Selesai"
endif

@enduml
