@startuml
|User|
start
:Login;
if (isAdmin?) then (no)
  
  :Pilih Pelajaran;
  :Buka Soal;
  while (Jawab Soal) is (belum selesai)
    :Jawab Soal;
  endwhile (selesai)
  :Kumpulkan Jawaban;
  :Lihat Hasil Ujian;
  stop
else (yes)
  |Admin|
  :Tambah Ujian;
  |System|
  :Simpan Ujian;
  |Admin|
  :Tambah Pelajaran;
  |System|
  :Simpan Pelajaran;
  |Admin|
  :Buat Kunci Jawaban;
  |System|
  :Simpan Kunci Jawaban;
  |Admin|
  stop
endif

|System|
fork
  :Simpan Jawaban;
fork again
  :Koreksi Jawaban;
end fork
@enduml
